name: Send cultural holiday notifications

on:
  # Run every day at 14:00 UTC (adjust to your preference)
  schedule:
    - cron: "0 14 * * *"
  # Allow manual runs with an optional dry_run flag
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Set to 1 to test without sending pushes"
        required: false
        default: "0"

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Call Supabase Edge Function
        env:
          FUNCTION_URL: ${{ secrets.SUPABASE_FUNCTION_URL }}
          SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          # If launched manually, use the provided dry_run; otherwise 0
          DRY_RUN: ${{ github.event.inputs.dry_run || '0' }}
        run: |
          set -euo pipefail

          if [ -z "${FUNCTION_URL:-}" ] || [ -z "${SERVICE_ROLE_KEY:-}" ]; then
            echo "❌ Missing SUPABASE_FUNCTION_URL or SUPABASE_SERVICE_ROLE_KEY secrets."
            exit 1
          fi

          echo "→ Hitting function: ${FUNCTION_URL}?dry_run=${DRY_RUN}"

          STATUS=$(curl -sS -o /tmp/resp.json -w "%{http_code}" \
            -X POST "${FUNCTION_URL}?dry_run=${DRY_RUN}" \
            -H "Authorization: Bearer ${SERVICE_ROLE_KEY}" \
            -H "Content-Type: application/json" \
            --data '{"source":"github-actions"}')

          echo "HTTP ${STATUS}"
          echo "Response:"
          cat /tmp/resp.json
          
          # Fail the job if the function did not return 2xx
          if [ "${STATUS}" -lt 200 ] || [ "${STATUS}" -ge 300 ]; then
            exit 1
          fi
